import * as github from '@actions/github';
import { PRFile } from './types';

export class GitHubService {
  private octokit: ReturnType<typeof github.getOctokit>;

  constructor(token: string) {
    this.octokit = github.getOctokit(token);
  }
  
  public getPRMetadata() {
    const { context } = github;

    if (!context.payload.pull_request) {
      throw new Error('This action can only be run on Pull Request events.');
    }

    const pr = context.payload.pull_request;
    
    return {
      owner: context.repo.owner,
      repo: context.repo.repo,
      pull_number: pr.number,
      title: pr.title,
      body: pr.body || '',
      author: pr.user?.login || 'unknown',
    };
  }

  public async getChangedFiles(): Promise<PRFile[]> {
    const meta = this.getPRMetadata();
    
    const { data: files } = await this.octokit.rest.pulls.listFiles({
      owner: meta.owner,
      repo: meta.repo,
      pull_number: meta.pull_number,
      per_page: 100, 
    });

    const reviewableFiles = files.filter(file => {
      const excludedExtensions = ['.png', '.jpg', '.jpeg', '.gif', '.svg', '.lock'];
      const isExcluded = excludedExtensions.some(ext => file.filename.endsWith(ext));
      return !isExcluded && file.status !== 'removed';
    });

    return reviewableFiles as PRFile[];
  }
  public async getCommitMessages(): Promise<string[]> {
    const meta = this.getPRMetadata();
    
    const { data: commits } = await this.octokit.rest.pulls.listCommits({
      owner: meta.owner,
      repo: meta.repo,
      pull_number: meta.pull_number,
      per_page: 100,
    });

    return commits.map(commitObj => commitObj.commit.message);
  }
  public async createOrUpdateReviewComment(body: string): Promise<void> {
    const meta = this.getPRMetadata();
    
    const { data: comments } = await this.octokit.rest.issues.listComments({
      owner: meta.owner,
      repo: meta.repo,
      issue_number: meta.pull_number,
    });

    const existingComment = comments.find(comment => 
      comment.user?.login === 'github-actions[bot]' && 
      comment.body?.includes('Auto-generated by [PRPilot]')
    );

    if (existingComment) {
      await this.octokit.rest.issues.updateComment({
        owner: meta.owner,
        repo: meta.repo,
        comment_id: existingComment.id,
        body,
      });
    } else {
      await this.octokit.rest.issues.createComment({
        owner: meta.owner,
        repo: meta.repo,
        issue_number: meta.pull_number,
        body,
      });
    }
  }
}
