import { RuleResult } from './types';

export class ReportGenerator {

  public generateMarkdown(results: RuleResult[]): string {
    const failedRules = results.filter(r => !r.pass);
    
    if (failedRules.length === 0) {
      return '### PRPilot Review: All Checks Passed!\n\nGood work! No issues were detected.';
    }

    let report = `### PRPilot Review: Issues Detected\n\n`;
    report += `Things that might need your attention before merging:\n\n`;

    for (const result of failedRules) {
      report += `#### ${result.ruleName}\n`;
      for (const warning of result.warnings) {
        report += `- ${warning}\n`;
      }
      report += '\n';
    }

    report += `---\n*Auto-generated by [PRPilot](https://github.com/Talha12Shiekh/prpilot)*`;
    return report;
  }
}